# This is mean to be the "default" configuration for
# our Prometheus install. For a more dynamic configuration
# we will mount a data volume container over this file.
global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: panopticon-dev

rule_files:

scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 5s
  static_configs:
    - targets: ['localhost:9090']

- job_name: 'node_exporter'
  scrape_interval: 5s
  metrics_path: /node
  static_configs:
    - targets: ['localhost:8080']

- job_name: 'cadvisor'
  scrape_interval: 5s
  metrics_path: /cadvisor
  static_configs:
    - targets: ['localhost:8080']

- job_name: 'consul'
  scrape_interval: 5s
  metrics_path: /consul
  static_configs:
    - targets: ['localhost:8080']

- job_name: 'consul-err'
  scrape_interval: 5s
  metrics_path: /consul_err
  static_configs:
    - targets: ['localhost:8080']

- job_name: 'gluster_node1'
  scrape_interval: 5s
  metrics_path: /gluster_node1
  static_configs:
    - targets: ['localhost:8080']

- job_name: 'gluster_node2'
  scrape_interval: 5s
  metrics_path: /gluster_node2
  static_configs:
    - targets: ['localhost:8080']

- job_name: 'weave'
  scrape_interval: 5s
  metrics_path: /weave
  static_configs:
    - targets: ['localhost:8080']

